/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated/requests'
import { Route as AuthenticatedRechargeRouteImport } from './routes/_authenticated/recharge'
import { Route as AuthenticatedRcPrintRouteImport } from './routes/_authenticated/rc-print'
import { Route as AuthenticatedRationPrintRouteImport } from './routes/_authenticated/ration-print'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedManageServicesRouteImport } from './routes/_authenticated/manage-services'
import { Route as AuthenticatedDlPrintRouteImport } from './routes/_authenticated/dl-print'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAapleSarkarRouteImport } from './routes/_authenticated/aaple-sarkar'
import { Route as AuthenticatedAadhaarToPanRouteImport } from './routes/_authenticated/aadhaar-to-pan'
import { Route as ApiPublicPaytmReturnRouteImport } from './routes/api/public/paytm-return'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRechargeRoute = AuthenticatedRechargeRouteImport.update({
  id: '/recharge',
  path: '/recharge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRcPrintRoute = AuthenticatedRcPrintRouteImport.update({
  id: '/rc-print',
  path: '/rc-print',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRationPrintRoute =
  AuthenticatedRationPrintRouteImport.update({
    id: '/ration-print',
    path: '/ration-print',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManageServicesRoute =
  AuthenticatedManageServicesRouteImport.update({
    id: '/manage-services',
    path: '/manage-services',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDlPrintRoute = AuthenticatedDlPrintRouteImport.update({
  id: '/dl-print',
  path: '/dl-print',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAapleSarkarRoute =
  AuthenticatedAapleSarkarRouteImport.update({
    id: '/aaple-sarkar',
    path: '/aaple-sarkar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAadhaarToPanRoute =
  AuthenticatedAadhaarToPanRouteImport.update({
    id: '/aadhaar-to-pan',
    path: '/aadhaar-to-pan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPaytmReturnRoute = ApiPublicPaytmReturnRouteImport.update({
  id: '/api/public/paytm-return',
  path: '/api/public/paytm-return',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/aadhaar-to-pan': typeof AuthenticatedAadhaarToPanRoute
  '/aaple-sarkar': typeof AuthenticatedAapleSarkarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dl-print': typeof AuthenticatedDlPrintRoute
  '/manage-services': typeof AuthenticatedManageServicesRoute
  '/members': typeof AuthenticatedMembersRoute
  '/ration-print': typeof AuthenticatedRationPrintRoute
  '/rc-print': typeof AuthenticatedRcPrintRoute
  '/recharge': typeof AuthenticatedRechargeRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/api/public/paytm-return': typeof ApiPublicPaytmReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/aadhaar-to-pan': typeof AuthenticatedAadhaarToPanRoute
  '/aaple-sarkar': typeof AuthenticatedAapleSarkarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dl-print': typeof AuthenticatedDlPrintRoute
  '/manage-services': typeof AuthenticatedManageServicesRoute
  '/members': typeof AuthenticatedMembersRoute
  '/ration-print': typeof AuthenticatedRationPrintRoute
  '/rc-print': typeof AuthenticatedRcPrintRoute
  '/recharge': typeof AuthenticatedRechargeRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/api/public/paytm-return': typeof ApiPublicPaytmReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/aadhaar-to-pan': typeof AuthenticatedAadhaarToPanRoute
  '/_authenticated/aaple-sarkar': typeof AuthenticatedAapleSarkarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dl-print': typeof AuthenticatedDlPrintRoute
  '/_authenticated/manage-services': typeof AuthenticatedManageServicesRoute
  '/_authenticated/members': typeof AuthenticatedMembersRoute
  '/_authenticated/ration-print': typeof AuthenticatedRationPrintRoute
  '/_authenticated/rc-print': typeof AuthenticatedRcPrintRoute
  '/_authenticated/recharge': typeof AuthenticatedRechargeRoute
  '/_authenticated/requests': typeof AuthenticatedRequestsRoute
  '/_authenticated/services': typeof AuthenticatedServicesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/api/public/paytm-return': typeof ApiPublicPaytmReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/aadhaar-to-pan'
    | '/aaple-sarkar'
    | '/dashboard'
    | '/dl-print'
    | '/manage-services'
    | '/members'
    | '/ration-print'
    | '/rc-print'
    | '/recharge'
    | '/requests'
    | '/services'
    | '/settings'
    | '/wallet'
    | '/api/public/paytm-return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/aadhaar-to-pan'
    | '/aaple-sarkar'
    | '/dashboard'
    | '/dl-print'
    | '/manage-services'
    | '/members'
    | '/ration-print'
    | '/rc-print'
    | '/recharge'
    | '/requests'
    | '/services'
    | '/settings'
    | '/wallet'
    | '/api/public/paytm-return'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/aadhaar-to-pan'
    | '/_authenticated/aaple-sarkar'
    | '/_authenticated/dashboard'
    | '/_authenticated/dl-print'
    | '/_authenticated/manage-services'
    | '/_authenticated/members'
    | '/_authenticated/ration-print'
    | '/_authenticated/rc-print'
    | '/_authenticated/recharge'
    | '/_authenticated/requests'
    | '/_authenticated/services'
    | '/_authenticated/settings'
    | '/_authenticated/wallet'
    | '/api/public/paytm-return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicPaytmReturnRoute: typeof ApiPublicPaytmReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recharge': {
      id: '/_authenticated/recharge'
      path: '/recharge'
      fullPath: '/recharge'
      preLoaderRoute: typeof AuthenticatedRechargeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rc-print': {
      id: '/_authenticated/rc-print'
      path: '/rc-print'
      fullPath: '/rc-print'
      preLoaderRoute: typeof AuthenticatedRcPrintRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ration-print': {
      id: '/_authenticated/ration-print'
      path: '/ration-print'
      fullPath: '/ration-print'
      preLoaderRoute: typeof AuthenticatedRationPrintRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manage-services': {
      id: '/_authenticated/manage-services'
      path: '/manage-services'
      fullPath: '/manage-services'
      preLoaderRoute: typeof AuthenticatedManageServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dl-print': {
      id: '/_authenticated/dl-print'
      path: '/dl-print'
      fullPath: '/dl-print'
      preLoaderRoute: typeof AuthenticatedDlPrintRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aaple-sarkar': {
      id: '/_authenticated/aaple-sarkar'
      path: '/aaple-sarkar'
      fullPath: '/aaple-sarkar'
      preLoaderRoute: typeof AuthenticatedAapleSarkarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aadhaar-to-pan': {
      id: '/_authenticated/aadhaar-to-pan'
      path: '/aadhaar-to-pan'
      fullPath: '/aadhaar-to-pan'
      preLoaderRoute: typeof AuthenticatedAadhaarToPanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/paytm-return': {
      id: '/api/public/paytm-return'
      path: '/api/public/paytm-return'
      fullPath: '/api/public/paytm-return'
      preLoaderRoute: typeof ApiPublicPaytmReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAadhaarToPanRoute: typeof AuthenticatedAadhaarToPanRoute
  AuthenticatedAapleSarkarRoute: typeof AuthenticatedAapleSarkarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDlPrintRoute: typeof AuthenticatedDlPrintRoute
  AuthenticatedManageServicesRoute: typeof AuthenticatedManageServicesRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRoute
  AuthenticatedRationPrintRoute: typeof AuthenticatedRationPrintRoute
  AuthenticatedRcPrintRoute: typeof AuthenticatedRcPrintRoute
  AuthenticatedRechargeRoute: typeof AuthenticatedRechargeRoute
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRoute
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAadhaarToPanRoute: AuthenticatedAadhaarToPanRoute,
  AuthenticatedAapleSarkarRoute: AuthenticatedAapleSarkarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDlPrintRoute: AuthenticatedDlPrintRoute,
  AuthenticatedManageServicesRoute: AuthenticatedManageServicesRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRoute,
  AuthenticatedRationPrintRoute: AuthenticatedRationPrintRoute,
  AuthenticatedRcPrintRoute: AuthenticatedRcPrintRoute,
  AuthenticatedRechargeRoute: AuthenticatedRechargeRoute,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRoute,
  AuthenticatedServicesRoute: AuthenticatedServicesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicPaytmReturnRoute: ApiPublicPaytmReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
