/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutFlowRouteImport } from './routes/checkout-flow'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated/requests'
import { Route as AuthenticatedRechargeRouteImport } from './routes/_authenticated/recharge'
import { Route as AuthenticatedRcPrintRouteImport } from './routes/_authenticated/rc-print'
import { Route as AuthenticatedRationPrintRouteImport } from './routes/_authenticated/ration-print'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedManageServicesRouteImport } from './routes/_authenticated/manage-services'
import { Route as AuthenticatedGazetteRouteImport } from './routes/_authenticated/gazette'
import { Route as AuthenticatedDraftsRouteImport } from './routes/_authenticated/drafts'
import { Route as AuthenticatedDlPrintRouteImport } from './routes/_authenticated/dl-print'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAapleSarkarRequestsRouteImport } from './routes/_authenticated/aaple-sarkar-requests'
import { Route as AuthenticatedAapleSarkarRouteImport } from './routes/_authenticated/aaple-sarkar'
import { Route as AuthenticatedAadhaarToPanRouteImport } from './routes/_authenticated/aadhaar-to-pan'
import { Route as ApiPublicPaytmReturnRouteImport } from './routes/api/public/paytm-return'
import { Route as AuthenticatedAdminSiteRouteImport } from './routes/_authenticated/admin.site'
import { Route as AuthenticatedAdminSarkarServicesRouteImport } from './routes/_authenticated/admin.sarkar-services'
import { Route as AuthenticatedAdminPagesRouteImport } from './routes/_authenticated/admin.pages'
import { Route as AuthenticatedAdminGazetteRouteImport } from './routes/_authenticated/admin.gazette'
import { Route as AuthenticatedAdminGatewaysRouteImport } from './routes/_authenticated/admin.gateways'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutFlowRoute = CheckoutFlowRouteImport.update({
  id: '/checkout-flow',
  path: '/checkout-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRechargeRoute = AuthenticatedRechargeRouteImport.update({
  id: '/recharge',
  path: '/recharge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRcPrintRoute = AuthenticatedRcPrintRouteImport.update({
  id: '/rc-print',
  path: '/rc-print',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRationPrintRoute =
  AuthenticatedRationPrintRouteImport.update({
    id: '/ration-print',
    path: '/ration-print',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManageServicesRoute =
  AuthenticatedManageServicesRouteImport.update({
    id: '/manage-services',
    path: '/manage-services',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGazetteRoute = AuthenticatedGazetteRouteImport.update({
  id: '/gazette',
  path: '/gazette',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDraftsRoute = AuthenticatedDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDlPrintRoute = AuthenticatedDlPrintRouteImport.update({
  id: '/dl-print',
  path: '/dl-print',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAapleSarkarRequestsRoute =
  AuthenticatedAapleSarkarRequestsRouteImport.update({
    id: '/aaple-sarkar-requests',
    path: '/aaple-sarkar-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAapleSarkarRoute =
  AuthenticatedAapleSarkarRouteImport.update({
    id: '/aaple-sarkar',
    path: '/aaple-sarkar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAadhaarToPanRoute =
  AuthenticatedAadhaarToPanRouteImport.update({
    id: '/aadhaar-to-pan',
    path: '/aadhaar-to-pan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPaytmReturnRoute = ApiPublicPaytmReturnRouteImport.update({
  id: '/api/public/paytm-return',
  path: '/api/public/paytm-return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSiteRoute = AuthenticatedAdminSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSarkarServicesRoute =
  AuthenticatedAdminSarkarServicesRouteImport.update({
    id: '/sarkar-services',
    path: '/sarkar-services',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPagesRoute = AuthenticatedAdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminGazetteRoute =
  AuthenticatedAdminGazetteRouteImport.update({
    id: '/gazette',
    path: '/gazette',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGatewaysRoute =
  AuthenticatedAdminGatewaysRouteImport.update({
    id: '/gateways',
    path: '/gateways',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/checkout-flow': typeof CheckoutFlowRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/aadhaar-to-pan': typeof AuthenticatedAadhaarToPanRoute
  '/aaple-sarkar': typeof AuthenticatedAapleSarkarRoute
  '/aaple-sarkar-requests': typeof AuthenticatedAapleSarkarRequestsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dl-print': typeof AuthenticatedDlPrintRoute
  '/drafts': typeof AuthenticatedDraftsRoute
  '/gazette': typeof AuthenticatedGazetteRoute
  '/manage-services': typeof AuthenticatedManageServicesRoute
  '/members': typeof AuthenticatedMembersRoute
  '/ration-print': typeof AuthenticatedRationPrintRoute
  '/rc-print': typeof AuthenticatedRcPrintRoute
  '/recharge': typeof AuthenticatedRechargeRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/admin/gateways': typeof AuthenticatedAdminGatewaysRoute
  '/admin/gazette': typeof AuthenticatedAdminGazetteRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/sarkar-services': typeof AuthenticatedAdminSarkarServicesRoute
  '/admin/site': typeof AuthenticatedAdminSiteRoute
  '/api/public/paytm-return': typeof ApiPublicPaytmReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/checkout-flow': typeof CheckoutFlowRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/aadhaar-to-pan': typeof AuthenticatedAadhaarToPanRoute
  '/aaple-sarkar': typeof AuthenticatedAapleSarkarRoute
  '/aaple-sarkar-requests': typeof AuthenticatedAapleSarkarRequestsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dl-print': typeof AuthenticatedDlPrintRoute
  '/drafts': typeof AuthenticatedDraftsRoute
  '/gazette': typeof AuthenticatedGazetteRoute
  '/manage-services': typeof AuthenticatedManageServicesRoute
  '/members': typeof AuthenticatedMembersRoute
  '/ration-print': typeof AuthenticatedRationPrintRoute
  '/rc-print': typeof AuthenticatedRcPrintRoute
  '/recharge': typeof AuthenticatedRechargeRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/admin/gateways': typeof AuthenticatedAdminGatewaysRoute
  '/admin/gazette': typeof AuthenticatedAdminGazetteRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/sarkar-services': typeof AuthenticatedAdminSarkarServicesRoute
  '/admin/site': typeof AuthenticatedAdminSiteRoute
  '/api/public/paytm-return': typeof ApiPublicPaytmReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/checkout-flow': typeof CheckoutFlowRoute
  '/contact': typeof ContactRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/aadhaar-to-pan': typeof AuthenticatedAadhaarToPanRoute
  '/_authenticated/aaple-sarkar': typeof AuthenticatedAapleSarkarRoute
  '/_authenticated/aaple-sarkar-requests': typeof AuthenticatedAapleSarkarRequestsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dl-print': typeof AuthenticatedDlPrintRoute
  '/_authenticated/drafts': typeof AuthenticatedDraftsRoute
  '/_authenticated/gazette': typeof AuthenticatedGazetteRoute
  '/_authenticated/manage-services': typeof AuthenticatedManageServicesRoute
  '/_authenticated/members': typeof AuthenticatedMembersRoute
  '/_authenticated/ration-print': typeof AuthenticatedRationPrintRoute
  '/_authenticated/rc-print': typeof AuthenticatedRcPrintRoute
  '/_authenticated/recharge': typeof AuthenticatedRechargeRoute
  '/_authenticated/requests': typeof AuthenticatedRequestsRoute
  '/_authenticated/services': typeof AuthenticatedServicesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/admin/gateways': typeof AuthenticatedAdminGatewaysRoute
  '/_authenticated/admin/gazette': typeof AuthenticatedAdminGazetteRoute
  '/_authenticated/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/_authenticated/admin/sarkar-services': typeof AuthenticatedAdminSarkarServicesRoute
  '/_authenticated/admin/site': typeof AuthenticatedAdminSiteRoute
  '/api/public/paytm-return': typeof ApiPublicPaytmReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/checkout-flow'
    | '/contact'
    | '/privacy-policy'
    | '/refund-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/aadhaar-to-pan'
    | '/aaple-sarkar'
    | '/aaple-sarkar-requests'
    | '/admin'
    | '/dashboard'
    | '/dl-print'
    | '/drafts'
    | '/gazette'
    | '/manage-services'
    | '/members'
    | '/ration-print'
    | '/rc-print'
    | '/recharge'
    | '/requests'
    | '/services'
    | '/settings'
    | '/wallet'
    | '/admin/gateways'
    | '/admin/gazette'
    | '/admin/pages'
    | '/admin/sarkar-services'
    | '/admin/site'
    | '/api/public/paytm-return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/checkout-flow'
    | '/contact'
    | '/privacy-policy'
    | '/refund-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/aadhaar-to-pan'
    | '/aaple-sarkar'
    | '/aaple-sarkar-requests'
    | '/admin'
    | '/dashboard'
    | '/dl-print'
    | '/drafts'
    | '/gazette'
    | '/manage-services'
    | '/members'
    | '/ration-print'
    | '/rc-print'
    | '/recharge'
    | '/requests'
    | '/services'
    | '/settings'
    | '/wallet'
    | '/admin/gateways'
    | '/admin/gazette'
    | '/admin/pages'
    | '/admin/sarkar-services'
    | '/admin/site'
    | '/api/public/paytm-return'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/checkout-flow'
    | '/contact'
    | '/privacy-policy'
    | '/refund-policy'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/aadhaar-to-pan'
    | '/_authenticated/aaple-sarkar'
    | '/_authenticated/aaple-sarkar-requests'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/dl-print'
    | '/_authenticated/drafts'
    | '/_authenticated/gazette'
    | '/_authenticated/manage-services'
    | '/_authenticated/members'
    | '/_authenticated/ration-print'
    | '/_authenticated/rc-print'
    | '/_authenticated/recharge'
    | '/_authenticated/requests'
    | '/_authenticated/services'
    | '/_authenticated/settings'
    | '/_authenticated/wallet'
    | '/_authenticated/admin/gateways'
    | '/_authenticated/admin/gazette'
    | '/_authenticated/admin/pages'
    | '/_authenticated/admin/sarkar-services'
    | '/_authenticated/admin/site'
    | '/api/public/paytm-return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CheckoutFlowRoute: typeof CheckoutFlowRoute
  ContactRoute: typeof ContactRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiPublicPaytmReturnRoute: typeof ApiPublicPaytmReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-flow': {
      id: '/checkout-flow'
      path: '/checkout-flow'
      fullPath: '/checkout-flow'
      preLoaderRoute: typeof CheckoutFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recharge': {
      id: '/_authenticated/recharge'
      path: '/recharge'
      fullPath: '/recharge'
      preLoaderRoute: typeof AuthenticatedRechargeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rc-print': {
      id: '/_authenticated/rc-print'
      path: '/rc-print'
      fullPath: '/rc-print'
      preLoaderRoute: typeof AuthenticatedRcPrintRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ration-print': {
      id: '/_authenticated/ration-print'
      path: '/ration-print'
      fullPath: '/ration-print'
      preLoaderRoute: typeof AuthenticatedRationPrintRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manage-services': {
      id: '/_authenticated/manage-services'
      path: '/manage-services'
      fullPath: '/manage-services'
      preLoaderRoute: typeof AuthenticatedManageServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gazette': {
      id: '/_authenticated/gazette'
      path: '/gazette'
      fullPath: '/gazette'
      preLoaderRoute: typeof AuthenticatedGazetteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drafts': {
      id: '/_authenticated/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof AuthenticatedDraftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dl-print': {
      id: '/_authenticated/dl-print'
      path: '/dl-print'
      fullPath: '/dl-print'
      preLoaderRoute: typeof AuthenticatedDlPrintRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aaple-sarkar-requests': {
      id: '/_authenticated/aaple-sarkar-requests'
      path: '/aaple-sarkar-requests'
      fullPath: '/aaple-sarkar-requests'
      preLoaderRoute: typeof AuthenticatedAapleSarkarRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aaple-sarkar': {
      id: '/_authenticated/aaple-sarkar'
      path: '/aaple-sarkar'
      fullPath: '/aaple-sarkar'
      preLoaderRoute: typeof AuthenticatedAapleSarkarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aadhaar-to-pan': {
      id: '/_authenticated/aadhaar-to-pan'
      path: '/aadhaar-to-pan'
      fullPath: '/aadhaar-to-pan'
      preLoaderRoute: typeof AuthenticatedAadhaarToPanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/paytm-return': {
      id: '/api/public/paytm-return'
      path: '/api/public/paytm-return'
      fullPath: '/api/public/paytm-return'
      preLoaderRoute: typeof ApiPublicPaytmReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/site': {
      id: '/_authenticated/admin/site'
      path: '/site'
      fullPath: '/admin/site'
      preLoaderRoute: typeof AuthenticatedAdminSiteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sarkar-services': {
      id: '/_authenticated/admin/sarkar-services'
      path: '/sarkar-services'
      fullPath: '/admin/sarkar-services'
      preLoaderRoute: typeof AuthenticatedAdminSarkarServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pages': {
      id: '/_authenticated/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AuthenticatedAdminPagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/gazette': {
      id: '/_authenticated/admin/gazette'
      path: '/gazette'
      fullPath: '/admin/gazette'
      preLoaderRoute: typeof AuthenticatedAdminGazetteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/gateways': {
      id: '/_authenticated/admin/gateways'
      path: '/gateways'
      fullPath: '/admin/gateways'
      preLoaderRoute: typeof AuthenticatedAdminGatewaysRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminGatewaysRoute: typeof AuthenticatedAdminGatewaysRoute
  AuthenticatedAdminGazetteRoute: typeof AuthenticatedAdminGazetteRoute
  AuthenticatedAdminPagesRoute: typeof AuthenticatedAdminPagesRoute
  AuthenticatedAdminSarkarServicesRoute: typeof AuthenticatedAdminSarkarServicesRoute
  AuthenticatedAdminSiteRoute: typeof AuthenticatedAdminSiteRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminGatewaysRoute: AuthenticatedAdminGatewaysRoute,
  AuthenticatedAdminGazetteRoute: AuthenticatedAdminGazetteRoute,
  AuthenticatedAdminPagesRoute: AuthenticatedAdminPagesRoute,
  AuthenticatedAdminSarkarServicesRoute: AuthenticatedAdminSarkarServicesRoute,
  AuthenticatedAdminSiteRoute: AuthenticatedAdminSiteRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAadhaarToPanRoute: typeof AuthenticatedAadhaarToPanRoute
  AuthenticatedAapleSarkarRoute: typeof AuthenticatedAapleSarkarRoute
  AuthenticatedAapleSarkarRequestsRoute: typeof AuthenticatedAapleSarkarRequestsRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDlPrintRoute: typeof AuthenticatedDlPrintRoute
  AuthenticatedDraftsRoute: typeof AuthenticatedDraftsRoute
  AuthenticatedGazetteRoute: typeof AuthenticatedGazetteRoute
  AuthenticatedManageServicesRoute: typeof AuthenticatedManageServicesRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRoute
  AuthenticatedRationPrintRoute: typeof AuthenticatedRationPrintRoute
  AuthenticatedRcPrintRoute: typeof AuthenticatedRcPrintRoute
  AuthenticatedRechargeRoute: typeof AuthenticatedRechargeRoute
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRoute
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAadhaarToPanRoute: AuthenticatedAadhaarToPanRoute,
  AuthenticatedAapleSarkarRoute: AuthenticatedAapleSarkarRoute,
  AuthenticatedAapleSarkarRequestsRoute: AuthenticatedAapleSarkarRequestsRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDlPrintRoute: AuthenticatedDlPrintRoute,
  AuthenticatedDraftsRoute: AuthenticatedDraftsRoute,
  AuthenticatedGazetteRoute: AuthenticatedGazetteRoute,
  AuthenticatedManageServicesRoute: AuthenticatedManageServicesRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRoute,
  AuthenticatedRationPrintRoute: AuthenticatedRationPrintRoute,
  AuthenticatedRcPrintRoute: AuthenticatedRcPrintRoute,
  AuthenticatedRechargeRoute: AuthenticatedRechargeRoute,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRoute,
  AuthenticatedServicesRoute: AuthenticatedServicesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CheckoutFlowRoute: CheckoutFlowRoute,
  ContactRoute: ContactRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiPublicPaytmReturnRoute: ApiPublicPaytmReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
